### ISSUE TITLE
"The underlying connection was closed: An unexpected error occurred on a receive." from Receipt GetMessage()

### ISSUE THREAD

**Issue by wwang109** [Moneris/Moneris-Gateway-API-dotNet#9]
We process transactions daily and we are noticing that through-out the day we have transactions that just randomly fail and returns this error.
It seem to have started happening more frequently after October 28th.
seem to happen up to 1-3% of our daily transactions.
We could not find any network issue on our end, and would like to know if this is something on Moneris connection or if there is some sort of cap on number of transactions.

**Comment by DavidJoyal** [comment]
I also have the same problem since the 29 of october. Our team is looking thru our network and can't seem to find any problem.

**Comment by zackakay** [comment]
We are also seeing the exact same issue on our implementation. Requests are succeeding immediately before and after seeing this message from Moneris.

**Comment by DavidJoyal** [comment]
After a lot of back and forth with Moneris support, they confirmed that they changed something on their side which corrected the problem. Haven't had any error since today (21 november)

**Comment by wwang109** [comment]
@DavidJoyal Thank you for getting this resolve!
I also do not see any more connection error on our end.
I do not have direct contact with Moneris support and have to wait on other people to deal with it.
